### PR TITLE
Scipy factorial

### PR DESCRIPTION
**Pull request by arokem**
Should fix this build error: https://travis-ci.org/uwescience/pulse2percept/builds/543060364#L1361

### CODE REVIEW

**Comment by arokem** [comment]
Hmm. Apparently needs a rebase.

**Comment by arokem** [comment]
Also adds numba and dask to the requirements file.

**Comment by arokem** [comment]
OK. Now rebased. Let's see if it passes CI.

**Comment by mbeyeler** [comment]
Great, thanks!!

**Pull request merged**
