### PR TITLE
fixTests

### PR DESCRIPTION
**Pull request by mbeyeler**
Making the tests pass again. Also fixing flake8 complaints.

### CODE REVIEW

**Comment by arokem** [comment]
Still no joy on Python 2.

I can make a pull request to get rid of this kind of PEP8 error:

https://travis-ci.org/uwescience/pulse2percept/jobs/168773085#L404

**Comment by arokem** [comment]
We're in 🇬🇱 !

**Comment by arokem** [comment]
Ready to merge?

**Comment by mbeyeler** [comment]
Yes, i think so! :+1:

**Pull request merged**
